### ISSUE TITLE
Development branch

### ISSUE THREAD

**Issue by thomasfinstad** [Foltik/terraform-provider-vyos#5]
I have been unable to work on this for a long time now, but I think I will get something done the next week and what I wish to propose is, in my mind, a good idea, but would benefit from extensive testing.

Just a simple dev branch would be helpful I think. What do you think?

**Comment by foltik** [comment]
Yeah that would be a good idea, I'm going to be working on this again in the near future as well. I've added you as a collaborator on the repo so you should have access now.

**Comment by thomasfinstad** [comment]
I just got back from easter vacation yesterday and was too slow to accept the invite.

**Comment by foltik** [comment]
Just sent again
